name: BUILD SERVICENODE

on:
  workflow_dispatch:
    inputs:
      image:
        description: Name of wallet.
        required: true
        default: servicenode
      version:
        description: Tag or version of an image
        required: true
      branch:
        description: branch
        required: true

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.docker_password }} | docker login --username ${{ secrets.docker_username }} --password-stdin

    # Build images
    - name: INFO BUILD
      run: echo ${{ github.event.inputs.image }} ${{ github.event.inputs.version }} ${{ github.event.inputs.branch }}
    - name: build an image
      run: ./ci.sh build ${{ github.event.inputs.image }} ${{ github.event.inputs.version }} ${{ github.event.inputs.branch }}
    - name: Run a container
      run: ./ci.sh run ${{ github.event.inputs.image }} ${{ github.event.inputs.version }}
    - name: Test build
      run: ./ci.sh test ${{ github.event.inputs.image }} ${{ github.event.inputs.version }}
    - name: Remove a container
      run: ./ci.sh clean ${{ github.event.inputs.image }} ${{ github.event.inputs.version }}
    - name: Remove dangling images
      if: ${{ always() }}
      run: yes | docker image prune
    - name: Push an image to DockerHub
      run: ./ci.sh push ${{ github.event.inputs.image }} ${{ github.event.inputs.version }}

#  staging:
#    if: ${{ github.event.pull_request }}
#    needs: build
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Test new image
#      run: echo "Some test"
