name: RELEASE IMAGE

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of wallet
        required: true
      version:
        description: Tag or version of an image
        required: true

jobs:

  release:
    runs-on: self-hosted

    steps:
    - name: Login to DockerHub
      run: echo ${{ secrets.docker_password }} | docker login --username ${{ secrets.docker_username }} --password-stdin
    - name: INFO RELEASE
      run: echo ${{ github.event.inputs.name }} ${{ github.event.inputs.version }}
    - name: Push an image to DockerHub
      run: ./ci.sh release ${{ github.event.inputs.name }} ${{ github.event.inputs.version }}
